from __future__ import annotations

from typing import Protocol

from app.schemas.critic import CriticReviewDTO
from app.schemas.ids import CriticReviewId, CurriculumId, GoalId, RunId


class CriticReviewRepository(Protocol):
    def create(self, critic_review: CriticReviewDTO) -> CriticReviewDTO: ...

    def save(self, critic_review: CriticReviewDTO) -> CriticReviewDTO: ...

    def get_by_id(self, critic_review_id: CriticReviewId) -> CriticReviewDTO: ...

    def list_by_goal_id(self, goal_id: GoalId) -> list[CriticReviewDTO]: ...

    def list_by_run_id(self, run_id: RunId) -> list[CriticReviewDTO]: ...

    def list_by_curriculum_id(self, curriculum_id: CurriculumId) -> list[CriticReviewDTO]: ...

    def clear(self) -> None: ...
