from __future__ import annotations

from typing import Protocol

from app.schemas.enums import QuizAttemptStatus, QuizStatus
from app.schemas.ids import AttemptId, CurriculumId, GoalId, QuizId
from app.schemas.quiz import QuizAttemptDTO, QuizDTO


class QuizRepository(Protocol):
    def create_quiz(self, quiz: QuizDTO) -> QuizDTO: ...

    def save_quiz(self, quiz: QuizDTO) -> QuizDTO: ...

    def get_quiz_by_id(self, quiz_id: QuizId) -> QuizDTO: ...

    def list_quizzes_by_goal_id(self, goal_id: GoalId) -> list[QuizDTO]: ...

    def list_quizzes_by_curriculum_id(self, curriculum_id: CurriculumId) -> list[QuizDTO]: ...

    def update_quiz_status(self, quiz_id: QuizId, status: QuizStatus) -> QuizDTO: ...

    def create_attempt(self, attempt: QuizAttemptDTO) -> QuizAttemptDTO: ...

    def save_attempt(self, attempt: QuizAttemptDTO) -> QuizAttemptDTO: ...

    def get_attempt_by_id(self, quiz_attempt_id: AttemptId) -> QuizAttemptDTO: ...

    def list_attempts_by_quiz_id(self, quiz_id: QuizId) -> list[QuizAttemptDTO]: ...

    def list_attempts_by_goal_id(self, goal_id: GoalId) -> list[QuizAttemptDTO]: ...

    def list_attempts_by_curriculum_id(
        self,
        curriculum_id: CurriculumId,
    ) -> list[QuizAttemptDTO]: ...

    def update_attempt_status(
        self,
        quiz_attempt_id: AttemptId,
        status: QuizAttemptStatus,
    ) -> QuizAttemptDTO: ...

    def clear(self) -> None: ...
